-- gitly_schema.sql
-- This file defines the database schema for the Gitly application.

-- Table for logging user activity
-- This table stores a record of user interactions with the application,
-- such as a visit to the dashboard. The `created_at` column uses
-- the `CURRENT_TIMESTAMP` to automatically record the time of the log.
CREATE TABLE IF NOT EXISTS activity_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    path TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for storing AI-generated insights
-- This table holds insights generated by the AI for specific repositories.
-- Each insight is tied to a user and a repository.
CREATE TABLE IF NOT EXISTS ai_insights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    repo_name TEXT NOT NULL,
    insight TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table for caching repository data
-- This table is used to cache repository information to avoid making
-- repeated API calls to GitHub. The `repo_data` is stored as a JSON string.
CREATE TABLE IF NOT EXISTS cached_repos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    repo_full_name TEXT NOT NULL,
    repo_data TEXT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, repo_full_name)
);
